import 'package:powersync/powersync.dart';

const Schema schema = Schema([
  Table('households', [
    Column.text('name'),
    Column.text('currency'),
    Column.integer('default_month_start_day'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.text('deleted_at'),
  ]),
  Table('financial_periods', [
    Column.text('household_id'),
    Column.text('name'),
    Column.text('start_date'),
    Column.text('end_date'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('users', [
    Column.text('household_id'),
    Column.text('shared_household_id'),
    Column.text('first_name'),
    Column.text('role'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.text('deleted_at'),
  ]),
  Table('accounts', [
    Column.text('household_id'),
    Column.text('owner_id'),
    Column.text('name'),
    Column.text('type'),
    Column.integer('is_public'), // SQLite uses integer for booleans
    Column.integer('is_default'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.text('deleted_at'),
  ]),
  Table('budgets', [
    Column.text('household_id'),
    Column.text('account_id'),
    Column.text('name'),
    Column.integer('default_amount'),
    Column.text('icon'),
    Column.text('color'),
    Column.integer('is_default'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.text('deleted_at'),
  ]),
  Table('categories', [
    Column.text('household_id'),
    Column.text('name'),
    Column.text('icon'),
    Column.text('color'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.text('deleted_at'),
  ]),
  Table('projects', [
    Column.text('household_id'),
    Column.text('account_id'),
    Column.text('name'),
    Column.integer('target_amount'),
    Column.integer('is_pinned_to_dashboard'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.text('deleted_at'),
  ]),
  Table('transactions', [
    Column.text('household_id'),
    Column.text('account_id'),
    Column.text('budget_id'),
    Column.text('category_id'),
    Column.text('project_id'),
    Column.text('created_by'),
    Column.integer('amount'),
    Column.text('transaction_date'),
    Column.text('description'),
    Column.text('type'),
    Column.text('status'),
    Column.integer('is_reconciliation'),
    Column.integer('ignore_in_balances'),
    Column.text('linked_transaction_id'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.text('deleted_at'),
  ]),
  Table('recurring_templates', [
    Column.text('household_id'),
    Column.text('account_id'),
    Column.text('budget_id'),
    Column.text('project_id'),
    Column.integer('amount'),
    Column.text('description'),
    Column.text('type'),
    Column.text('cron_schedule'),
    Column.text('next_execution_date'),
    Column.integer('is_active'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.text('deleted_at'),
  ]),
  Table('notifications', [
    Column.text('household_id'),
    Column.text('user_id'),
    Column.text('title'),
    Column.text('body'),
    Column.text('type'),
    Column.integer('is_read'),
    Column.text('metadata'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.text('deleted_at'),
  ]),
]);
